version: "3.7"
services:
  app:
    image: golang:1.14.3
    container_name: app
    volumes: 
      - ./app:/go/src/app
      - ./.aws:/root/.aws
    
    working_dir: /go/src/app
    tty: true
  # ses:
  #   image: tvial/docker-mailserver:latest
  #   container_name: ses
  #   environment:
  #     - ENABLE_SPAMASSASSIN=1
  #     - SPAMASSASSIN_SPAM_TO_INBOX=1
  #     - ENABLE_CLAMAV=1
  #     - ENABLE_FAIL2BAN=1
  #     - ENABLE_POSTGREY=1
  #     - ONE_DIR=1
  #     - DMS_DEBUG=0
