version: "3.7"
services:
  dynamodbClient:
    image: golang:1.13.1
    container_name: dynamodbClient
    volumes:
      - ./app:/go/src/app
    working_dir: /go/src/app
    tty: true
  dynamodbAdmin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodbAdmin
    ports: 
      - 8001:8001
    environment: 
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - DYNAMO_ENDPOINT=dynamodb:8000 # dynamodb 不能大寫
  dynamodb:
    image: amazon/dynamodb-local:1.11.477
    container_name: dynamodb
    ports:
      - 8000:8000