version: "3.7"
services:
  dynamodbClient:
    image: golang:1.13.1
    container_name: dynamodbClient
    volumes:
      - ./app:/go/src/app
      - ./.aws:/root/.aws
    working_dir: /go/src/app
    tty: true
  dynamodbAdmin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodbAdmin
    ports: 
      - 8001:8001
    environment: 
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - DYNAMO_ENDPOINT=dynamodb:8000 # dynamodb 不能大寫
  dynamodb:
    image: amazon/dynamodb-local:1.11.477
    container_name: dynamodb
    ports:
      - 8000:8000
  awscli:
    image: jhaoheng/docker-awscli
    volumes: 
      - ./.aws:/root/.aws
      - ./awscli:/home/awscli
    working_dir: /home/awscli
    container_name: awscli
    depends_on: 
      - dynamodb
    command: sh -c "chmod +x /home/awscli/entrypoint.sh && sh /home/awscli/entrypoint.sh"
    tty: true