version: "3.7"
services:
  app:
    image: golang:1.13.1
    container_name: app
    volumes: 
      - ./.aws:/root/.aws
      - ./:/go/src/app
    working_dir: /go/src/app
    tty: true
  awscli:
    image: jhaoheng/docker-awscli
    volumes:
      - ./.aws:/root/.aws
    container_name: awscli
    tty: true

  sqs:
    image: roribio16/alpine-sqs
    container_name: sqs
    ports:
      - 9324:9324
      - 9325:9325
      
  sns:
    image: s12v/sns
    container_name: sns
    ports:
      - 9911:9911
    volumes:
      - ./sns-config/db.json:/etc/sns/db.json
    depends_on: 
      - sqs
    command: sh -c "sleep 6s && java -jar /sns.jar"