version: "3.7"
services:
  app:
    image: golang:1.13.1
    container_name: app
    volumes: 
      - ./app:/go/src/app
      - ./release:/go/src/release
    working_dir: /go/src
    # command: GOOS=linux GOARCH=amd64 go build -o main main.go
    tty: true
  lambda:
    image: lambci/lambda:go1.x
    container_name: lambda
    environment: 
      - DOCKER_LAMBDA_STAY_OPEN=1
      - DOCKER_LAMBDA_WATCH=1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_REGION=us-east-1
      - _HANDLER=main # handler 名稱
      - AWS_LAMBDA_FUNCTION_NAME=main
    ports: 
      - 9001:9001
    volumes: 
      - ./release:/var/task:ro,delegated
  awscli:
    image: jhaoheng/docker-awscli
    container_name: awscli
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    tty: true